# Generated by Django 5.0.2 on 2024-02-09 23:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mbr_master', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='area',
            name='unidad',
        ),
        migrations.AddField(
            model_name='unidad',
            name='area',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mbr_master.area'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='unidad',
            name='subarea',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mbr_master.subarea'),
            preserve_default=False,
        ),
    ]
