# Generated by Django 5.0.1 on 2024-02-05 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mbr_master', '0002_alter_users_managers_remove_users_photo_and_more'),
        ('mbr_master', '0002_banco'),
    ]

    operations = [
    ]
