# Generated by Django 5.0.2 on 2024-02-17 06:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mbr_master', '0002_subarea_remove_area_unidad_unidad_area_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoComprobante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TipoGasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Gasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_serie', models.CharField(max_length=50)),
                ('concepto', models.CharField(max_length=255)),
                ('fecha_comprobante', models.DateField()),
                ('numero_comprobante', models.CharField(max_length=50)),
                ('ruc_dni', models.CharField(max_length=20)),
                ('nombre_razon_social', models.CharField(max_length=255)),
                ('direccion', models.CharField(max_length=255)),
                ('distrito', models.CharField(max_length=100)),
                ('provincia', models.CharField(max_length=100)),
                ('departamento', models.CharField(max_length=100)),
                ('pais', models.CharField(max_length=100)),
                ('tipo_compra', models.CharField(max_length=100)),
                ('orden_compra', models.CharField(max_length=100)),
                ('fecha_vencimiento', models.DateField()),
                ('moneda', models.CharField(max_length=10)),
                ('comentarios', models.TextField(blank=True, null=True)),
                ('total_comprobante', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tipo_comprobante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mbr_master.tipocomprobante')),
                ('tipo_gasto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mbr_master.tipogasto')),
            ],
        ),
    ]
